import { Item, mallPrice, print } from "kolmafia";
import { $item, have } from "libram";


const mrStoreItems: [Item, number][] = [
  [$item`Apathargic Bandersnatch`, 0],
  [$item`fairy-worn boots`, 0],
  [$item`Source terminal`, 0],
  [$item`Kramco Industries packing carton`, 0],
  [$item`baby camelCalf`, 0],
  [$item`emotion chip`, 0],
  [$item`packaged backup camera`, 0],
  [$item`packaged cold medicine cabinet`, 0],
  [$item`packaged Jurassic Parka`, 0],
  [$item`book of facts`, 0],
  [$item`boxed bat wings`, 0],
  [$item`Tome of Clip Art`, 1],
  [$item`Pack of Every Card`, 1],
  [$item`LI-11 Motor Pool voucher`, 1],
  [$item`corked genie bottle`, 1],
  [$item`Pocket Meteor Guide`, 1],
  [$item`space planula`, 1],
  [$item`January's Garbage Tote (unopened)`, 1],
  [$item`Fourth of May Cosplay Saber kit`, 1],
  [$item`packaged Pocket Professor`, 1],
  [$item`mint-in-box Powerful Glove`, 1],
  [$item`Comprehensive Cartographic Compendium`, 1],
  [$item`packaged miniature crystal ball`, 1],
  [$item`packaged industrial fire extinguisher`, 1],
  [$item`grey gosling`, 1],
  [$item`undrilled cosmic bowling ball`, 1],
  [$item`boxed autumn-aton`, 1],
  [$item`sleeping patriotic eagle`, 1],
  [$item`closed-circuit pay phone`, 1],
  [$item`cursed monkey glove`, 1],
  [$item`shrink-wrapped Cincho de Mayo`, 1],
  [$item`shrink-wrapped 2002 Mr. Store Catalog`, 1],
  [$item`wrapped candy cane sword cane`, 1],
  [$item`baby chest mimic`, 1],
  [$item`in-the-box spring shoes`, 1],
  [$item`packaged Everfull Dart Holster`, 1],
  [$item`boxed Apriling band helmet`, 1],
  [$item`packaged Roman Candelabra`, 1],
  [$item`boxed Sept-Ember Censer`, 1],
  [$item`McHugeLarge deluxe ski set`, 1],
  [$item`Clan VIP Lounge invitation`, 2],
  [$item`Schmalz's First Prize Beer`, 2],
  [$item`Moping Artistic Goth Kid`, 2],
  [$item`The Smith's Tome`, 2],
  [$item`Granny Tood's Thanksgarden Catalog`, 2],
  [$item`Witchess Set`, 2],
  [$item`heart-shaped crate`, 2],
  [$item`suspicious package`, 2],
  [$item`xo-skeleton-in-a-box`, 2],
  [$item`Neverending Party invitation envelope`, 2],
  [$item`latte lovers club card`, 2],
  [$item`voter registration form`, 2],
  [$item`mint condition Lil' Doctor™ bag`, 2],
  [$item`unopened diabolic pizza cube box`, 2],
  [$item`Unopened Eight Days a Week Pill Keeper`, 2],
  [$item`combat lover's locket lockbox`, 2],
  [$item`packaged model train set`, 2],
  [$item`boxed august scepter`, 2],
  [$item`boxed Mayam Calendar`, 2],
  [$item`Sealed TakerSpace letter of Marque`, 2],
  [$item`Libram of Candy Heart Summoning`, 3],
  [$item`Libram of BRICKOs`, 3],
  [$item`Order of the Green Thumb Order Form`, 3],
  [$item`bottle of lovebug pheromones`, 3],
  [$item`Chateau Mantegna room key`, 3],
  [$item`yellow puck`, 3],
  [$item`yellow puck with a bow on it`, 3],
  [$item`machine elf capsule`, 3],
  [$item`disconnected intergnat`, 3],
  [$item`DIY protonic accelerator kit`, 3],
  [$item`li'l orphan tot`, 3],
  [$item`potted tea tree`, 3],
  [$item`X-32-F snowman crate`, 3],
  [$item`kitten burglar`, 3],
  [$item`red-spotted snapper roe`, 3],
  [$item`bagged Cargo Cultist Shorts`, 3],
  [$item`packaged familiar scrapbook`, 3],
  [$item`power seed`, 3],
  [$item`packaged Daylight Shavings Helmet`, 3],
  [$item`bottled Vampire Vintner`, 3],
  [$item`mint condition magnifying glass`, 3],
  [$item`undamaged Unbreakable Umbrella`, 3],
  [$item`packaged June cleaver`, 3],
  [$item`unopened tiny stillsuit`, 3],
  [$item`mummified entombed cookbookbat`, 3],
  [$item`Rock Garden Guide`, 3],
  [$item`peace turkey outline`, 3],
  [$item`miniscule temporal rip`, 4],
  [$item`Tome of Snowcone Summoning`, 4],
  [$item`navel ring of navel gazing`, 4],
  [$item`Libram of Divine Favors`, 4],
  [$item`sane hatrack`, 4],
  [$item`spooky rattling cigar box`, 4],
  [$item`container of Spooky Putty`, 4],
  [$item`floaty stone sphere`, 4],
  [$item`Libram of Love Songs`, 4],
  [$item`panicked kernel`, 4],
  [$item`Crown of Thrones`, 4],
  [$item`Greatest American Pants`, 4],
  [$item`a cute angel`, 4],
  [$item`Mint Salton Pepper's Peppermint Seed Catalog`, 4],
  [$item`mysterious chest`, 4],
  [$item`Camp Scout backpack`, 4],
  [$item`can of Rain-Doh`, 4],
  [$item`Libram of Resolutions`, 4],
  [$item`Unagnimated Gnome`, 4],
  [$item`avatar of the Unconscious Collective`, 4],
  [$item`deanimated reanimator's coffin`, 4],
  [$item`Libram of Pulled Taffy`, 4],
  [$item`Buddy Bjorn`, 4],
  [$item`fist turkey outline`, 4],
  [$item`Little Geneticist DNA-Splicing Lab`, 4],
  [$item`still grill`, 4],
  [$item`shrine to the Barrel god`, 4],
  [$item`haunted doghouse`, 4],
  [$item`portable Mayo Clinic`, 4],
  [$item`Dear Past Self Package`, 4],
  [$item`LT&T telegraph office deed`, 4],
  [$item`New-You Club Membership Form`, 4],
  [$item`pantogram`, 4],
  [$item`unpowered Robortender`, 4],
  [$item`Bastille Battalion control rig crate`, 4],
  [$item`Boxing Day care package`, 4],
  [$item`SongBoom™ BoomBox Box`, 4],
  [$item`Beach Comb Box`, 4],
  [$item`rune-strewn spoon cocoon`, 4],
  [$item`vampyric cloake pattern`, 4],
  [$item`packaged knock-off retro superhero cape`, 4],
  [$item`unopened Bird-a-Day calendar`, 4],
  [$item`shortest-order cook`, 4],
  [$item`designer sweatpants (new old stock)`, 4],
  [$item`S.I.T. Course Completion Certificate`, 4],
  [$item`Dark Jill-of-All-Trades`, 4],
  [$item`Black and White Apron Enrollment Form`, 4],
  [$item`CyberRealm keycode`, 4],
];

const tierValues = new Map<number, number>([
  [0, 20],
  [1, 11],
  [2, 6],
  [3, 3],
  [4, 1],
]);

export function itemPriceValue() {
  // Filter out items the player already owns
  const filteredItems = mrStoreItems
    .filter(([item]) => !have(item))
    .map(([item, tier]) => {
      const turnsSaved = tierValues.get(tier) ?? Infinity;
      const price = mallPrice(item);
      const pricePerTurn = turnsSaved !== Infinity ? price / turnsSaved : Infinity;

      return { item, tier, pricePerTurn };
    })
    .filter(({ pricePerTurn }) => pricePerTurn !== Infinity) // Remove invalid entries
    .sort((a, b) => a.pricePerTurn - b.pricePerTurn); // Sort by pricePerTurn (ascending)

  // Print the sorted list
  filteredItems.forEach(({ item, tier, pricePerTurn }) => {
    print(`Item: ${item}, Tier: ${tier}, Price per turn saved: ${pricePerTurn.toFixed(2)}`);
  });
}
